apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wedding
  name: wedding-registration-api-deployment
  labels:
    app: wedding-registration-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wedding-registration-api
  template:
    metadata:
      labels:
        app: wedding-registration-api
    spec:
      containers:
        - name: wedding-registration-api
          image: ghcr.io/lucascarioca/wedding-registration-services:latest
          ports:
            - containerPort: 80
              name: w-r-s-http
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: wedding-pg
                  key: API_KEY
            - name: ENV
                valueFrom:
                  secretKeyRef:
                    name: wedding-pg
                    key: ENV
            - name: PG_DB
                valueFrom:
                  secretKeyRef:
                    name: wedding-pg
                    key: PG_DB
            - name: PG_HOST
                valueFrom:
                  secretKeyRef:
                    name: wedding-pg
                    key: PG_HOST
            - name: PG_PASS
                valueFrom:
                  secretKeyRef:
                    name: wedding-pg
                    key: PG_PASS
            - name: PG_PORT
                valueFrom:
                  secretKeyRef:
                    name: wedding-pg
                    key: PG_PORT
            - name: PG_SSL
                valueFrom:
                  secretKeyRef:
                    name: wedding-pg
                    key: PG_SSL
            - name: PG_TIMEZONE
                valueFrom:
                  secretKeyRef:
                    name: wedding-pg
                    key: PG_TIMEZONE
            - name: PG_USER
                valueFrom:
                  secretKeyRef:
                    name: wedding-pg
                    key: PG_USER
---
apiVersion: v1
kind: Service
metadata:
  namespace: wedding
  name: wedding-registration-api-service
spec:
  type: NodePort
  ports:
    - name: tcp
      port: 80
      nodePort: 30003
      targetPort: w-r-s-http
  selector:
    app: wedding-registration-api
