name: CICD
on:
  push:
jobs:
  ci:
    uses: LucasCarioca/workflows/.github/workflows/ci-go.yml@v0.6.0
    with:
      go-version: 1.18
      lint: false
  release:
    needs: ci
    uses: LucasCarioca/workflows/.github/workflows/release-docker.yml@v0.10.1
    with:
      registry: ghcr.io
      image_name: lucascarioca/wedding-registration-services
    secrets:
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}