name: Promote -> DO
on:
  workflow_dispatch:
jobs:
  release:
    if: github.ref == 'refs/heads/main'
    uses: LucasCarioca/workflows/.github/workflows/release-do.yml@v0.7.0
    with:
      config-files: k8s/do/
      registry: ghcr.io
      image_name: lucascarioca/wedding-registration-services
      deployment: wedding-service
      container: wedding-service
      namespace: wedding
    secrets:
      kube_config: ${{ secrets.DO_KUBE_CONFIG }}
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}